var hierarchy =
[
    [ "Activity", "class_activity.html", null ],
    [ "Activity_Data", "struct_activity___data.html", null ],
    [ "Battery", "class_battery.html", null ],
    [ "BuzzerNote", "struct_buzzer_note.html", null ],
    [ "Config", "struct_config.html", null ],
    [ "Config_app_compass", "struct_config__app__compass.html", null ],
    [ "Config_app_microphone", "struct_config__app__microphone.html", null ],
    [ "Config_custom_binary", "struct_config__custom__binary.html", null ],
    [ "Config_haptics", "struct_config__haptics.html", null ],
    [ "Config_mqtt", "struct_config__mqtt.html", null ],
    [ "Config_widget_battery", "struct_config__widget__battery.html", null ],
    [ "Config_widget_open_weather", "struct_config__widget__open__weather.html", null ],
    [ "connect_responder", "structconnect__responder.html", null ],
    [ "Display", "class_display.html", null ],
    [ "Haptics", "class_haptics.html", null ],
    [ "IMU", "class_i_m_u.html", null ],
    [ "RTC", "class_r_t_c.html", null ],
    [ "scan_responder", "structscan__responder.html", null ],
    [ "Settings", "class_settings.html", null ],
    [ "SettingsOptionBool", "class_settings_option_bool.html", null ],
    [ "SettingsOptionFloat", "class_settings_option_float.html", null ],
    [ "SettingsOptionInt", "class_settings_option_int.html", null ],
    [ "SettingsOptionString", "class_settings_option_string.html", null ],
    [ "TinyWATCH", "class_tiny_w_a_t_c_h.html", null ],
    [ "touch_event_t", "structtouch__event__t.html", null ],
    [ "TT_Time", "struct_t_t___time.html", null ],
    [ "tw_app", "classtw__app.html", [
      [ "AppCompass", "class_app_compass.html", null ],
      [ "AppEmpty", "class_app_empty.html", null ],
      [ "AppMicrophone", "class_app_microphone.html", null ]
    ] ],
    [ "tw_control", "classtw__control.html", [
      [ "ControlButton", "class_control_button.html", null ],
      [ "ControlLabel", "class_control_label.html", null ],
      [ "ControlToggle", "class_control_toggle.html", null ],
      [ "ControlValue", "class_control_value.html", null ],
      [ "ControlValueSlider", "class_control_value_slider.html", null ]
    ] ],
    [ "tw_face", "classtw__face.html", [
      [ "FaceAppList", "class_face_app_list.html", null ],
      [ "FaceBatteryEmpty", "class_face_battery_empty.html", null ],
      [ "FaceBoot", "class_face_boot.html", null ],
      [ "FaceEmpty", "class_face_empty.html", null ],
      [ "FaceIMU", "class_face_i_m_u.html", null ],
      [ "FaceNotifications", "class_face_notifications.html", null ],
      [ "FaceSettings", "class_face_settings.html", null ],
      [ "FaceSystem", "class_face_system.html", null ],
      [ "FaceWatchSettings", "class_face_watch_settings.html", null ],
      [ "FaceWatch_CustomBinary", "class_face_watch___custom_binary.html", null ],
      [ "FaceWatch_CustomWindows", "class_face_watch___custom_windows.html", null ],
      [ "FaceWatch_DefaultAnalog", "class_face_watch___default_analog.html", null ],
      [ "FaceWatch_DefaultDigital", "class_face_watch___default_digital.html", null ]
    ] ],
    [ "tw_widget", "classtw__widget.html", [
      [ "WidgetActivityRing", "class_widget_activity_ring.html", null ],
      [ "WidgetBattery", "class_widget_battery.html", null ],
      [ "WidgetESP32", "class_widget_e_s_p32.html", null ],
      [ "WidgetMessage", "class_widget_message.html", null ],
      [ "WidgetOpenWeather", "class_widget_open_weather.html", null ],
      [ "WidgetWifi", "class_widget_wifi.html", null ]
    ] ],
    [ "WebServer", "class_web_server.html", null ],
    [ "WifiController::wifi_callback_item", "struct_wifi_controller_1_1wifi__callback__item.html", null ],
    [ "wifi_station", "structwifi__station.html", null ],
    [ "WifiController::wifi_task_item", "struct_wifi_controller_1_1wifi__task__item.html", null ],
    [ "WifiController", "class_wifi_controller.html", null ],
    [ "WifiSetup", "class_wifi_setup.html", null ],
    [ "FaceWatch_CustomWindows::WindowsClockSettings", "struct_face_watch___custom_windows_1_1_windows_clock_settings.html", null ]
];